# Data paths
input_folder: "gharchive-2015-01"
parquet_file: "gharchive_jan5_11.parquet"

# Analysis settings
week_days: [5, 6, 7, 8, 9, 10, 11]  # January 5-11
event_type_for_repo_analysis: "PushEvent"

# Plot settings
line_plot:
  title: "Average GitHub Events per Hour – Jan 5-11, 2015"
  xlabel: "Hour of Day"
  ylabel: "Average Number of Events"

bar_plot:
  title: "Top 10 Repositories by PushEvents – Jan 5-11, 2015"
  xlabel: "Repository"
  ylabel: "Number of PushEvents"
